version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/zachbaker.dev
hooks:
  BeforeInstall:
    - location: deploy/preinstall.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: deploy/postinstall.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: deploy/start.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: deploy/stop.sh
      timeout: 300
      runas: ubuntu
permissions:
  - object: /home/ubuntu/zachbaker.dev
    pattern: "**"
    owner: ubuntu
    mode: 777
    type:
      - file
