name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: ${{ vars.AWS_REGION }}
      - run: |
          echo "Deploying branch ${{ env.GITHUB_REF }} to ${{ github.event.inputs.environment }}"
          commit_hash=`git rev-parse HEAD`
          deployment_id=`aws deploy create-deployment --application-name zachbaker.dev --deployment-group-name main --github-location repository=$GITHUB_REPOSITORY,commitId=$commit_hash --ignore-application-stop-failures`
          aws deploy wait deployment-successful --deployment-id $deployment_id
